script: bundle exec rake spec

matrix:
  include:
    - rvm: 1.8.7
      env: SKIP_PEDANT=true
      gemfile: gemfiles/gemfile.no-pedant
    - rvm: 1.9.3
    - rvm: jruby-19mode
      env: SKIP_PEDANT=true
      gemfile: gemfiles/gemfile.no-pedant
    - rvm: 2.0.0
  allow_failures:
    - rvm: 1.8.7
    - rvm: jruby-19mode
    - rvm: 1.9.3
      gemfile: gemfiles/gemfile.latest-pedant
